name: React build apple
on:
  push:
    branches:
      - develop

jobs:
  React-Build-ssh-action:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: 14.4.75.234
          username: test
          password: TEST
          port: 10101
          timeout: 40s # 30초 기본
          script: |
            echo "테스트 출력"
